### ISSUE TITLE
Possible values for $o-assets-global-path?

### ISSUE THREAD

**Issue by kaelig** [Financial-Times/o-assets#17]
The code mentions:

```scss
		// defaults to use module name
		$full-path: $module + '/' + $full-path;
		// Only add the global path if a custom path hasn't been set
		@if ($o-assets-global-path) {
			$full-path: $o-assets-global-path + $full-path;
		}
```

Unfortunately I couldn't find any occurrences where `$o-assets-global-path` could be `false` or `null`.

…so it looks like an artifact of the past that should now be:

```scss
		// defaults to use module name
		$full-path: $o-assets-global-path + $module + '/' + $full-path;
```

Thoughts?
